name: main
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_VERSION: "12.x"
  FLUTTER_VERSION: "3.0.5"
  MELOS_VERSION: "1.1.2"

jobs:
  builds:
    name: Build APK
  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub get
      - run: flutter test
      - name: Install melos  
        run: dart pub global activate melos ${{env.MELOS_VERSION}}

      - name: Run build_runner
        run: make sync

      - name: Run Unit Test
        run: make test

      - name: Check format
        run: make format

      - name: Run analyze
        run: make analyze
      - run: flutter build apk --debug --split-per-abi
